### ISSUE TITLE
Archive SEGV when destination folder does not exist

### ISSUE THREAD

**Issue by chris-crone** [deislabs/porter#1169]
## Describe the bug
When running `porter bundle archive folder-does-not-exist/bundle.tgz`, Porter segfaults.

## To Reproduce
1. Use any porter.yaml
1. Run `porter bundle archive folder-does-not-exist/bundle.tgz`
1. Segfault

## Expected behavior
Either Porter should: (1) error out saying the destination folder does not exist, or (2) create the destination folder.

I think that (1) is preferred.

## Porter Command and Output
```
$ porter bundle archive archive/kubecon-eu-2020.tgz
ERRO[0008] Can't add file /var/folders/cb/156z21pd32g06x7s9p3v7g9r0000gn/T/kubecon-eu-2020-0.1.0857665579/artifacts/layout/blobs/sha256/0b8eaf929c06a2baf68481a231287c519c58765d93125dfd53c7d0dd0641a336 to tar: io: read/write on closed pipe 
ERRO[0008] Can't close tar writer: io: read/write on closed pipe 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x106cba2]

goroutine 1 [running]:
io.copyBuffer(0x0, 0x0, 0x2aafd40, 0xc00000e090, 0xc0009f2000, 0x8000, 0x8000, 0x19, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.10/x64/src/io/io.go:404 +0x1d2
io.Copy(...)
        /opt/hostedtoolcache/go/1.13.10/x64/src/io/io.go:364
get.porter.sh/porter/pkg/porter.(*exporter).export(0xc0005e9b38, 0x0, 0x0)
        /home/vsts/work/1/s/pkg/porter/archive.go:130 +0x6a4
get.porter.sh/porter/pkg/porter.(*Porter).Archive(0xc000178160, 0x28141e0, 0xb, 0xc00027adc0, 0x11, 0x0, 0x0, 0x7ffeefbff98e, 0x1b, 0x0, ...)
        /home/vsts/work/1/s/pkg/porter/archive.go:70 +0x25c
main.buildBundleArchiveCommand.func2(0xc000256dc0, 0xc000254f60, 0x1, 0x1, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/porter/bundle.go:342 +0x7e
github.com/spf13/cobra.(*Command).execute(0xc000256dc0, 0xc000254f30, 0x1, 0x1, 0xc000256dc0, 0xc000254f30)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ee000, 0x0, 0x2503a20, 0xc000092058)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
        /home/vsts/work/1/s/cmd/porter/main.go:18 +0x27
```

## Version
porter v0.27.2 (aee93e98)

I didn't try with a `HEAD:main` as the build failed on my machine with:
```
$ make build
GO111MODULE=on go mod tidy
warning: ignoring symlink /Users/chris/work/porter/src/github.com/deislabs/porter/docs/themes/porter/assets
go: github.com/vdice/cnab-go@v0.0.0-20200604175151-7484e185ff27: invalid version: unknown revision 7484e185ff27
make: *** [generate] Error 1
```

**Comment by chris-crone** [comment]
Thanks :)

**Comment by vdice** [comment]
Thank you for filing the issue @chris-crone !  By the way, when convenient, can you try building Porter from main again?  If you still encounter issue(s), we can help out asap.

**Comment by chris-crone** [comment]
Seems to build now but I do get some shell script errors at the start:

```console
$ make
bash: -c: line 0: syntax error in conditional expression: unexpected token `('
bash: -c: line 0: syntax error near `?(*'
bash: -c: line 0: `if [[ "${PATH}" == ?(*:)"/Users/chris/go/bin"?([:,/:]*) ]];then echo ${GOPATH}/bin;fi'
```

I'm running on macOS with:
```console
$ echo $SHELL
/bin/zsh
$ /bin/zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

**Comment by carolynvs** [comment]
@simongdavies Can you take a look at what Chris is running into? It seems to be related to your Makefile change that just went in.
