### ISSUE TITLE
Docker host access flag causing panic

### ISSUE THREAD

**Issue by jdolitsky** [deislabs/porter#983]
## Describe the bug
The new `--allow-docker-host-access` flag causes a panic

## To Reproduce
1. Run `porter install` using the `--allow-docker-host-access` flag

## Expected behavior
No panic :)

## Porter Command and Output
```
$ porter install  --debug --allow-docker-host-access
...
Resolved storage plugin to storage.porter.filesystem
<my_homedir>/.porter/porter plugin run storage.porter.filesystem
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x229f483]

goroutine 1 [running]:
get.porter.sh/porter/pkg/cnab/provider.(*Runtime).dockerDriverWithHostAccess.func1(0xc0002fe8c0, 0xc00056ed80, 0x10, 0x10)
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/cnab/provider/driver.go:78 +0x33
github.com/cnabio/cnab-go/driver/docker.(*Driver).exec(0xc000402540, 0xc00042cd00, 0x0, 0x0, 0x0)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/cnabio/cnab-go@v0.10.1-beta1/driver/docker/docker.go:168 +0x4ed
github.com/cnabio/cnab-go/driver/docker.(*Driver).Run(0xc000402540, 0xc00042cd00, 0x3, 0xc00042cd00, 0x0)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/cnabio/cnab-go@v0.10.1-beta1/driver/docker/docker.go:38 +0x35
github.com/cnabio/cnab-go/action.(*Install).Run(0xc0006395b8, 0xc000301c70, 0xc000551620, 0xc0003c64e0, 0x3, 0x3, 0xc0003d18c0, 0xc0004549a0)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/cnabio/cnab-go@v0.10.1-beta1/action/install.go:31 +0x176
get.porter.sh/porter/pkg/cnab/provider.(*Runtime).Install(0xc00049b890, 0xc0002265f0, 0x9, 0xc0002a0c40, 0x11, 0xc0003d18f0, 0xc0003d18c0, 0xc0004549a0, 0x1, 0x1, ...)
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/cnab/provider/install.go:73 +0x8e6
get.porter.sh/porter/pkg/porter.(*Porter).InstallBundle(0xc0001ad400, 0x27f97ab, 0xb, 0xc0002a0c40, 0x11, 0x0, 0x0, 0xc0002265f0, 0x9, 0xc00019e800, ...)
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/porter/install.go:47 +0x3cf
main.buildBundleInstallCommand.func2(0xc00020b180, 0xc000207a00, 0x0, 0x10, 0x0, 0x0)
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/cmd/porter/bundle.go:114 +0x7e
github.com/spf13/cobra.(*Command).execute(0xc00020b180, 0xc000207700, 0x10, 0x10, 0xc00020b180, 0xc000207700)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002b2a00, 0x0, 0x24edbc0, 0xc00009c058)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/cmd/porter/main.go:18 +0x27
```

## Version
porter v0.26.0-beta.1 (b15c4109)

Tried using canary build, v0.26.0-beta.1-3-g1aa1a72f (1aa1a72f), and same error

**Comment by carolynvs** [comment]
To reproduce this use a bundle that doesn't have the following in the porter.yaml

```yaml
required:
- docker
```

Looks like when we added in the ability for bundles to say they need docker, in #977, that was when this was introduced.
